const MODULES = [
  "levels",
  "roles",
  "welcome",
  "moderation",
  "automod",
  "logs",
  "tickets",
  "suggestions",
  "events",
  "giveaways",
  "tempVoice",
  "scheduler",
  "customCommands",
  "achievements",
  "missions",
  "seasons",
  "prestige",
];
function defaultConfig() {
  return {
    general: { prefix: "!", locale: "pt-BR", timezone: "America/Sao_Paulo" },
    modules: Object.fromEntries(
      MODULES.map((name) => [name, ["levels", "roles"].includes(name)]),
    ),
    levels: {
      chat: { enabled: true, min: 15, max: 25, cooldownSeconds: 60 },
      voice: { enabled: true, min: 20, max: 35, intervalMinutes: 5 },
      blockedChannelIds: [],
      blockedRoleIds: [],
      channelMultipliers: {},
      roleMultipliers: {},
      levelUpChannelId: "",
      curve: {
        type: "progressive",
        base: 100,
        coefficient: 50,
        thresholds: [],
      },
      requireProgression: false,
      rewardMode: "highest",
    },
    rewards: [],
    progressions: [],
    appearance: {
      name: "Kagetsu",
      primary: "#b49aff",
      secondary: "#83beff",
      background: "#070910",
      backgroundUrl: "",
      logoUrl: "",
      barStyle: "rounded",
    },
    profile: { roleIds: [], labels: [], badges: [] },
    welcome: {
      channelId: "",
      message: "Bem-vindo {user} ao {server}!",
      type: "text",
      leaveChannelId: "",
      leaveMessage: "{username} saiu do servidor.",
      autoroleIds: [],
      delayMinutes: 0,
    },
    logs: { channels: {} },
    moderation: { warnRules: [] },
    automod: { whitelistRoleIds: [], whitelistChannelIds: [], rules: [] },
    tickets: { logChannelId: "" },
    suggestions: { channelId: "" },
    tempVoice: { triggerChannelId: "", categoryId: "" },
    prestige: { maxLevel: 100 },
  };
}
module.exports = { defaultConfig, MODULES };
